
version: "3"

services:
  db:
    container_name: controle_acoes_db
    image: postgres:13.0
    volumes:
      - ./docker_volumes:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always