# Generated by Django 3.1.3 on 2020-11-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_ir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='cotas_totais',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='valor_medio',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='lucro_ou_perda',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CarteiraAtivo',
        ),
    ]
